<?php

/**
 * Implements hook_form_alter().
 */
function simplenews_toggle_form_alter(&$form, &$form_state, $form_id) {
  // Add Simplenews settings to simplenews newsletter node form.
  if (strpos($form_id, 'simplenews_block_form') === 0) {
  	if ($form['mail']['#type'] == 'textfield') {
  		$form['submit']['#value'] = t('(un) Subscribe');
  	}
  	array_unshift($form['#submit'], 'simplenews_toggle_block_form_submit');
  }
}

function simplenews_toggle_block_form_submit($form, &$form_state) {
	if (simplenews_user_is_subscribed($form_state['values']['mail'],$form['#tid']))
		$form_state['values']['action'] = 'unsubscribe';
}


